try {
    console.log('success');
}
catch (error) {
    console.log(error);
}
finally {
    console.log('finally');
}
